# User config
author: "Femi Olukoya"
tagline: "Will code for food."
description: "Senior software engineer currently working Discord"
keywords: "Software"
email: "femi.was.taken@gmail.com"
linkedin: "https://www.linkedin.com/in/aquafemi"
instagram: "https://www.instagram.com/aquafemi"
soundcloud: "https://www.soundcloud.com/aquafemi"
mixcloud: "https://www.mixcloud.com/aquafemi"

# Site config
baseurl: ""
url: "http://femi.xyz"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed